class: net.gtaun.wl.lang.LanguagePlugin
name: WL Multi Language Support Plugin
version: 1.1-SNAPSHOT
buildNumber: ${build.number}
buildDate: ${build.timestamp}
authors: MK124, 123marvin123
description: 
